"""MedicalRecord and MedicalReport models."""
import enum
from datetime import datetime, timezone

from ..extensions import db


class RecordType(enum.Enum):
    LAB_REPORT = 'lab_report'
    IMAGING = 'imaging'
    PRESCRIPTION = 'prescription'
    DISCHARGE_SUMMARY = 'discharge_summary'
    VACCINATION = 'vaccination'
    INSURANCE = 'insurance'
    OTHER = 'other'


class MedicalRecord(db.Model):
    """A medical document uploaded by a patient or generated by the platform."""

    __tablename__ = 'medical_records'

    id = db.Column(db.Integer, primary_key=True)
    patient_id = db.Column(
        db.Integer, db.ForeignKey('users.id', ondelete='CASCADE'), nullable=False, index=True
    )
    record_type = db.Column(db.Enum(RecordType), nullable=False)
    title = db.Column(db.String(200), nullable=False)
    description = db.Column(db.Text)
    file_url = db.Column(db.String(500))
    file_name = db.Column(db.String(255))
    file_size = db.Column(db.Integer)  # bytes

    uploaded_by = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    is_confidential = db.Column(db.Boolean, default=False)

    created_at = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc), nullable=False)

    patient = db.relationship('User', foreign_keys=[patient_id], backref='medical_records')
    uploader = db.relationship('User', foreign_keys=[uploaded_by])

    def __repr__(self):
        return f'<MedicalRecord {self.title} patient={self.patient_id}>'
